apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
    - name: demo-service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
